version: 2.1

orbs:
  ft-golang-ci: financial-times/golang-ci@1

workflows:
  tests_and_docker:
    jobs:
      - ft-golang-ci/build-and-test:
          context:
            - cm-team-github
            - dockerhub-shared

  snyk-scanning:
    jobs:
      - ft-golang-ci/scan:
          context:
            - cm-team-github
            - cm-team-snyk
